version: '3'
networks:
  demo:
    external:
      name: demo
services:
    twaarhustrafficdata182955:
        hostname: AarhusTrafficData182955
        labels:
          stream.name: AarhusTrafficData182955
          stream.type: traffic
          stream.uuid: fc8edefb-3491-4f20-9b9c-fd0edc926b6c
          stream.run.uuid: c6f31374-b678-11e7-aa12-8c85902d2485
        container_name: AarhusTrafficData182955
        command: running/AarhusTrafficData182955.properties
        image: streamreasoning/twcitybench
        networks:
          - demo
        ports:
          - "4000:4000"
          - "4040:4040"
        volumes:
          - ./running/:/opt/tw/running:rw

    twaarhustrafficdata158505:
        hostname: AarhusTrafficData158505
        labels:
          stream.name: AarhusTrafficData158505
          stream.type: traffic
          stream.uuid: 05336a3c-3d3b-4173-a8c0-a416d65c372b
          stream.run.uuid: c6f31374-b678-11e7-aa12-8c85902d2485
        container_name: AarhusTrafficData158505
        command: running/AarhusTrafficData158505.properties
        image: streamreasoning/twcitybench
        networks:
          - demo
        ports:
          - "4001:4001"
          - "4041:4041"
        volumes:
          - ./running/:/opt/tw/running:rw

