version: '3'
services:
      postgres:
          labels:
           stream.run.uudi: f0ed2582-b62f-11e7-8f3e-784f43a5c461
          container_name: postgres
          build: ./postgres
          ports:
           - "5432:5432"
      dsaarhustrafficdata182955:
          labels:
            server.name: AarhusTrafficData182955
          container_name: dsaarhustrafficdata182955
          command: running/AarhusTrafficData182955.properties
          build: ./ontop/
          ports:
            - "9090:9090"
          volumes:
             - ./running/:/usr/local/streamer/running:rw

      twaarhustrafficdata182955:
          labels:
            stream.name: AarhusTrafficData182955
            stream.type: traffic
            stream.uuid: 676590b9-eecd-4da7-95a6-fca625afcec4
            stream.run.uuid: f0ed2582-b62f-11e7-8f3e-784f43a5c461
          container_name: AarhusTrafficData182955
          command: running/AarhusTrafficData182955.properties
          image: streamreasoning/twcitybench
          ports:
            - "4000:4000"
            - "4040:4040"
          volumes:
            - ./running/:/opt/tw/running:rw

      dsaarhustrafficdata158505:
          labels:
            server.name: AarhusTrafficData158505
          container_name: dsaarhustrafficdata158505
          command: running/AarhusTrafficData158505.properties
          build: ./ontop/
          ports:
            - "9091:9091"
          volumes:
             - ./running/:/usr/local/streamer/running:rw

      twaarhustrafficdata158505:
          labels:
            stream.name: AarhusTrafficData158505
            stream.type: traffic
            stream.uuid: ca93dc19-12bc-43b1-ba08-2a9cc1b527fe
            stream.run.uuid: f0ed2582-b62f-11e7-8f3e-784f43a5c461
          container_name: AarhusTrafficData158505
          command: running/AarhusTrafficData158505.properties
          image: streamreasoning/twcitybench
          ports:
            - "4001:4001"
            - "4041:4041"
          volumes:
            - ./running/:/opt/tw/running:rw

