version: '3'
networks:
  demo:
    external:
      name: demo
volumes:
  influxdata:
  grafanadb:
services:
    influxsrv:
      build: ./influxdb 
      container_name: influxsrv
      ports:
        - "8086:8086"
        - "8087:8086"
      volumes:
        - influxdata:/var/lib/influxdb:rw
      networks:
        - demo

    grafana:
      build: ./grafana
      container_name: grafana
      ports:
        - "3000:3000"
      links:
        - influxsrv:influxsrv
      volumes:
        - grafanadb:/var/lib/grafana
      environment:
        - INFLUXDB_HOST=influxsrv
        - INFLUXDB_PORT=8086
        - INFLUXDB_NAME=rspengines
        - INFLUXDB_USER=root
        - INFLUXDB_PASS=root
      networks:
        - demo

    notebook:
      build: ./rsplib
      links:
        - influxsrv:influxsrv
        - grafana:grafana
      ports:
        - "8888:8888"
      volumes:
        - /Users/andreamauri/rspdev/rsplab/collector/rsplib:/home/jovyan/work
      networks:
        - demo





































