influxsrv:
  build: ./influxdb
  container_name: influxsrv
  ports:
    - "8086:8086"
  volumes:
    - influxdata:/var/lib/influxdb:rw

grafana:
  build: ./grafana
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - influxsrv:influxsrv
  volumes:
    - grafanadb:/var/lib/grafana
  environment:
    - INFLUXDB_HOST=collector
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=rspengines
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root

notebook:
  container_name: rsplab
  image: streamreasoning/rsplab-notebook:latest
  links:
    - influxsrv:influxsrv
    - grafana:grafana
  ports:
    - "80:8888"
  volumes:
    - /Users/riccardo/_Projects/RSP/rsplab/collector/rsplib:/home/jovyan/work:rw
    - resultsdata:/home/jovyan/work/data


